[email]
sender_email = "taiccpartners@gmail.com"
app_password = "jpfnhxfodpxlznol"

GEMINI_API_KEY = "AIzaSyBewwPw1WoIYH_0m-qJ5RyYzo0vPpN5xMk"

SHEET_NAME = "AI_Readiness_Data"

[gcp_service_account]
type = "service_account"
project_id = "even-gear-471712-k6"
private_key_id = "0188e25511bacd7ef616228d87690338b1169360"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCqE4ANYTv664cd
JtDVoc7SoqIBZzH4BlYjSdZh05tE6A0ntsgUVeuVj7fr4v81u8SYWfpCsBHfwRE/
TZ7ZzwL6J7TNkgo7oaWN+y23djii36q7fsryBbCJDY8QSepYAM2tWL+1THPPDCiF
kjKx5mwJun4f7blyQoggQ9dAXEsqXwhmDzD0A/0rE7KXhIZCENRfxO2a+saH9cTC
0GCdz87HAiH6WXphsCct89y3PD9VZRUujrF1R6qViRbW2Cc/68DTu3WHrDvMM8DL
ueL+Wu2LICQvr06fTP4Eejo4xL9vvzbrHoy1+/5rn2H7/gNCJwNLr5urJChSqMt5
x9CkLO4FAgMBAAECggEAUVVj/oIKehOamNFQO2nXC5ok2YDtP4xgMx4DfOMCNPC4
Ic7iXf8821hQf2kd3Sd/e9BDwxKKabPduKU5GzZJWTIV391AMYY7Muv0z/CkYxeN
gX7ANP+Nje1DBmoivJUdxxFTFLOMCm7pDf99aOAluH1MBZ7c+YxhpvRqgufgNlFV
+4ME+F1O5y+CzPzqhHdKGPtug5Gxk62dj6uaPNyOyV0rYxLjU7LZPhuhFmGftpM7
6ceEPJIWM/acR4PA0ZhjvUugFgTLuq9oftKmzlOcIKeLJG185Fsatfcu/UmhlizE
5Vumn/qj+VInPOZfbLR3gzgAB3raDFdG3FQ8fNh+vQKBgQDhWhhm1JaAcBLXZ23s
+39ydFa7eKyLygE5LV7LzJk7ygoJZbjUlR9qj1ZeAf7X5NfUGx7Vo3C6iR77iwh4
oGCM/AE8kXQ1mbJleuSbzWqpBK4blA6qIe9Ont2p85OHPku8x0S4mS4YG3mHY+YJ
we7HQtebmDqyS9emMs14UIwtNwKBgQDBNOlIloz3IIwVYd4gs5czq0PKY7cGxdYE
yAlIOnAStxUN60goekC6yDeLvo3RwWjLpDLd0fe39Ps8yv+NpTHIRy4DEiFu2DJH
W+ItwWoeDPyeAToOKcXBfSto3wLRINNrnazjHtxK3TY+ME++mWc1SDE2JL6ABd/+
aG8iueb8owKBgG3tRhP7RcM3aGl9AallcWECkUB3+Ctkib47fI+LqX/56XV2EnhY
me+gJjBLZuYnsoS8CgmK5bWIp/1qb+Jv0UlUsMG77mUrKVPJY/UAejQinU/EpHan
gRXn9xctQ1zorYdT6RjnWA3YcSrzN0axPGolGAnFc3R//J0NER/MouR3AoGALcoI
b7eeeQMxr++d4Uouz4QLcO/o9KX2bvOpn4CaBxV02/OjClTO+nVxFKF4ovmfiIPF
umSEvQhGcsX5guxfvAOCmB+35LlAUUEpfYaVS8HwLNJFnA2yXIT5wMT5ue55rMuV
qc4qj2OV828ntxhMKYiOgTJ8I4NA7t55WFWOtNkCgYBA1RxPd5aWeOh9bJIEfmkS
uPEEYIEZvNdaT1cabGh6I0Ia1FqWKr0uekJqZryKQwkt9KlH2iKiXI16V7g43sAO
8dmLdNKl2JxDxplj9ZHPZKOfNBXXEznd70FsA4VC9n22Nm4taV4KVV9u9Y7Kr7FN
+M5WoVK6oPRiu4rCX7U4Ww==
-----END PRIVATE KEY-----"""
client_email = "streamlit-service-account@even-gear-471712-k6.iam.gserviceaccount.com"
client_id = "107459882380094237057"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-service-account%40even-gear-471712-k6.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

